=== splatch/osgi-cpm/admin/src/main/resources/policies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://code-house.org/cpm/admin"
    xmlns:tns="http://code-house.org/cpm/admin" elementFormDefault="qualified">

    <complexType name="policies">
        <sequence>
            <element name="policy" type="tns:policy" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="policy">
        <choice minOccurs="0" maxOccurs="unbounded">
            <element name="allow" type="tns:allow" />
            <element name="deny" type="tns:deny" />
        </choice>
    </complexType>

    <complexType name="allow">
        <complexContent>
            <extension base="tns:conditionContainer" />
        </complexContent>
    </complexType>

    <complexType name="deny">
        <complexContent>
            <extension base="tns:conditionContainer" />
        </complexContent>
    </complexType>

    <complexType name="conditionContainer" abstract="true">
        <sequence>
            <element name="condition" type="tns:condition" minOccurs="0" maxOccurs="unbounded" />
            <element name="permission" type="tns:permission" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="string" use="optional" />
    </complexType>

    <complexType name="condition">
        <sequence>
            <element name="argument" type="string" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="class" type="string" use="required" />
    </complexType>

    <complexType name="permission">
        <sequence>
            <element name="name" type="string" minOccurs="0" maxOccurs="1" />
            <element name="action" type="string" minOccurs="0" maxOccurs="1" />
        </sequence>
        <attribute name="class" type="string" use="required" />
    </complexType>

    <element name="policies" type="tns:policies" />

</schema>

=== splatch/osgi-cpm/admin/src/main/resources/policy.xml
<?xml version="1.0" encoding="utf-8" ?>
<policies xmlns="http://code-house.org/cpm/admin"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://code-house.org/cpm/admin policies.xsd">
    <policy>
        <allow>
            <condition class="org.osgi.service.condpermadmin.BundleLocationCondition">
                <argument>mvn:org.code-house.cpm/org.code-house.cpm.test/*</argument>
            </condition>
            <condition class="org.code_house.cpm.condition.PrincipalCondition">
                <argument>org.apache.karaf.jaas.boot.principal.RolePrincipal</argument>
                <argument>role_admin</argument>
            </condition>
            <permission class="org.osgi.framework.ServicePermission">
                <name>javax.servlet.http.HttpServlet</name>
                <action>get</action>
            </permission>
        </allow>
        <deny>
            <condition class="org.osgi.service.condpermadmin.BundleLocationCondition">
                <argument>mvn:org.code-house.cpm/org.code-house.cpm.test/*</argument>
            </condition>
            <permission class="org.osgi.framework.ServicePermission">
                <name>*</name>
                <action>get</action>
            </permission>
        </deny>
        <allow>
            <permission class="java.security.AllPermission">
                <name>*</name>
                <action>*</action>
            </permission>
        </allow>
    </policy>

</policies>
